#!/usr/bin/env python3

import skilstak.colors as c

def hello():
    """Print 'Hello, world!'"""
    print("Hello, World!")

def coloredword(word):
    """Print a multicolored word."""
    for char in word:
        print(c.rc() + char + c.x, end='')

if __name__ == '__main__':
    hello()
    print("Insert a word here to see a M U L T I C O L O R E D version.")
    word = input("> ")
    coloredword(word)
    print("")
